/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'zedar' at '13.05.15 23:06' with Gradle 2.4
 *
 * @author zedar, @date 13.05.15 23:06
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
